from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # -----------------------------------
        # main window
        MainWindow.setObjectName("MainWindow")
        # MainWindow.resize(660, 336)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 336))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 336))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        # -----------------------------------
        # buttons
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 20, 150, 25))
        self.pushButton.setObjectName("pushButton")
        self.close_server = QtWidgets.QPushButton(self.centralwidget)
        self.close_server.setGeometry(QtCore.QRect(170, 20, 150, 25))
        self.close_server.setObjectName("close_server")
        # -----------------------------------
        # tables
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 70, 560, 200))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget.setBaseSize(QtCore.QSize(0, 0))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(130)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_stat = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_stat.setGeometry(QtCore.QRect(600, 70, 280, 200))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_stat.sizePolicy().hasHeightForWidth())
        self.tableWidget_stat.setSizePolicy(sizePolicy)
        self.tableWidget_stat.horizontalHeader().setDefaultSectionSize(130)

        self.tableWidget_stat.setColumnCount(2)
        self.tableWidget_stat.setObjectName("tableWidget_stat")
        self.tableWidget_stat.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_stat.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_stat.setHorizontalHeaderItem(1, item)
        self.tableWidget_stat.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_stat.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_stat.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_stat.verticalHeader().setVisible(False)
        # -----------------------------------
        # labels
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 50, 200, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(600, 50, 200, 16))
        self.label_2.setObjectName("label_2")
        # -----------------------------------
        # menubar & menu
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 660, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())
        # -----------------------------------
        # statusbar
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Чат-сервер"))
        self.pushButton.setText(_translate("MainWindow", "Запустить сервер"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Пользователь"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Хост"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Дата последнего подключения"))
        self.label.setText(_translate("MainWindow", "Подключенные клиенты:"))
        self.label_2.setText(_translate("MainWindow", "Статистика пользователей:"))
        item = self.tableWidget_stat.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Пользователь"))
        item = self.tableWidget_stat.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Сообщений"))
        self.close_server.setText(_translate("MainWindow", "Остановить сервер"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.action.setText(_translate("MainWindow", "Настройки сервера"))
        self.action_2.setText(_translate("MainWindow", "Выход"))
